In [18]:
library(ggplot2)


library(readxl)


library(dplyr)

library(openxlsx)

Attaching package: 'dplyr'


The following objects are masked from 'package:stats':

    filter, lag


The following objects are masked from 'package:base':

    intersect, setdiff, setequal, union

In [50]:
blok_rye_dat = read_excel("D:\\Users\\User\\Documents\\BlokenRy.xlsx")

head(blok_rye_dat)

  ID   Blok Ry Fakke
1 1658 1    1  19
2 1659 1    2  21
3 1660 1    3  22
4 1661 1    4  24
5 1662 1    5  26
6 1663 1    6  28

In [51]:



## We want to see how many rows each blok of vineyards has:

rye_dat = as.data.frame(table(blok_rye_dat$Blok))

names(rye_dat) = c("Blok_nom", "Rye")

### Next we want to see the total amount of vakke each blok has.

vakke_dat <- aggregate(Fakke~Blok,blok_rye_dat,sum)

vak_ry_dat = cbind(rye_dat, vakke_dat[,2])

names(vak_ry_dat) = c("Blok_nom", "Rye" , "Vakke")


# print(vak_ry_dat)


# # Let's find out how much vines each blok has:

stokke_nom = rep(times = 26 , 7)

 stokke_nom[c(1, 20, 21)] = 4
 
mat = as.matrix(stokke_nom)




vak_ry_dat = as.matrix(vak_ry_dat)


vak_ry_dat = cbind(vak_ry_dat , mat)

colnames(vak_ry_dat) = c("Blok_nom", "Rye" , "Vakke" , "Vines_per_vak")

vak_ry_dat = as.data.frame(vak_ry_dat)

# Let's convert the columns of vak_ry_dat into numeric, except for the first column.



vak_ry_dat$Vakke = as.numeric(vak_ry_dat$Vakke)



vak_ry_dat$Rye = as.numeric(vak_ry_dat$Rye)


vak_ry_dat$Vines_per_vak = as.numeric(vak_ry_dat$Vines_per_vak)


## Let's create a column which indicates the number of vines for each block.


vak_ry_dat$Vines = vak_ry_dat$Vines_per_vak * vak_ry_dat$Rye * vak_ry_dat$Vakke



vak_ry_dat = vak_ry_dat[,!c(colnames(vak_ry_dat) == "Vines_per_vak")]

In [2]:
# Write the vak_ry_dat dataset into excel.



write.xlsx(vak_ry_dat , "G:\\My Drive\\Daniel\\data\\vak_ry_dat.xlsx")

ERROR: Error in write.xlsx(vak_ry_dat, "G:\\My Drive\\Daniel\\data\\vak_ry_dat.xlsx"): could not find function "write.xlsx"

# Creating the blok inligting dataset:

In [1]:
library(readxl)

#### We start by importing blok_info.xlsx dataset


1. This dataset will simply give us information on how to create our big dataset

In [2]:
# Let's now try to start to create the blok inligting dataset;


blok_rye_dat = as.data.frame(read_excel("G:\\My Drive\\Programming\\Datasets\\blok_info.xlsx"))




blok_rye_dat$Vines = blok_rye_dat$Vakke * blok_rye_dat$vines_per_vak


print(blok_rye_dat)

   Blok_nom Rye Vakke Vines vines_per_vak
1         1  35  1091  4364             4
2        10  27   882  6174             7
3        11  28   476  3332             7
4        12  24  1032  7224             7
5        13  25   375  2625             7
6        14  26   390  2730             7
7        15  27   308  2156             7
8        16  26   468  3276             7
9        17  26   486  3402             7
10       18  34  1020  7140             7
11       19  35  1050  7350             7
12        2  14   462  3234             7
13       20  38  1140  7980             7
14       21  28   996  6972             7
15       22  44  1156  8092             7
16       23  36  1123  7861             7
17       2b  14   462  3234             7
18        3  26   858  3432             4
19        4  27   891  3564             4
20        5  26   884  6188             7
21        6  26   884  6188             7
22        7  28   952  6664             7
23        8  26   858  6006             7
24        9   3    99   693             7
25       9a  11   363  2541             7
26       9b  13   429  3003             7

# Create stok_id and stok_nommer columns

In [42]:
# First let's create the stok_id; stok_nommer columns of the blok inligting dataset;

stok_id = 1:sum(blok_rye_dat$Vines)

message("This is how much vines we have on the farm")

length(stok_id)



stok_nommer = list()

for(i in 1:nrow(blok_rye_dat)){

stok_nommer[[i]] = rep(times = blok_rye_dat$Vines[i] /  blok_rye_dat$vines_per_vak[i] , 1:blok_rye_dat$vines_per_vak[i])

}


stok_nommer = unlist(stok_nommer, use.names = FALSE)   # unlisting vector

This is how much vines we have on the farm

[1] 125425

# Create blok_id ; blok_nommer columns;

In [43]:
## We put all of our items into a for loop and a list.


# Let's create the blok_nommer which will create a vector which indicate the blok numbers


#### blok_nommer vector ######


blok_nommer = list()


for(i in 1:nrow(blok_rye_dat)){

blok_nommer[[i]] = rep(times = blok_rye_dat$Vines[i], blok_rye_dat$Blok_nom[i])

}



blok_nommer = unlist(blok_nommer, use.names = FALSE)                          # unlisting blok_nommer list





####  Blok_id vector  #####


blok_id = list()


for(i in 1:nrow(blok_rye_dat)){

blok_id[[i]] = rep(times = blok_rye_dat$Vines[i], i)

}


blok_id = unlist(blok_id, use.names = FALSE)       # unlisting blok_id vector

# Create Vak_id ; Vak_nommer columns

In [49]:
head(blok_rye_dat)

  Blok_nom Rye Vakke Vines vines_per_vak
1 1        35  1091  4364  4
2 10       27   882  6174  7
3 11       28   476  3332  7
4 12       24  1032  7224  7
5 13       25   375  2625  7
6 14       26   390  2730  7

In [47]:
## 



# df <- data.frame (Stok_id = Stok_id , Stok_nommer = stok_nommer, Vak_id = vak_id , Ry_id = ry_id ,

#                    Ry_nommer = ry_nommer , Blok_id = blok_id , Blok_nommer = blok_nommer , blok_id = blok_id_vec )





blok_inligting_dat <- data.frame (stok_id = stok_id , blok_nommer = blok_nommer , blok_id = blok_id , blok_nommer = blok_nommer)

In [45]:
head(df)

  stok_id blok_nommer
1 1       1
2 2       1
3 3       1
4 4       1
5 5       1
6 6       1

In [5]:
table(blok_nommer_vec)

table(blok_id_vec)

blok_nommer_vec
   1   10   11   12   13   14   15   16   17   18   19    2   20   21   22   23
4364 6174 3332 7224 2625 2730 2156 3276 3402 7140 7350 3234 7980 6972 8092 7861
  2b    3    4    5    6    7    8    9   9a   9b
3234 3432 3564 6188 6188 6664 6006  693 2541 3003

blok_id_vec
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16
4364 6174 3332 7224 2625 2730 2156 3276 3402 7140 7350 3234 7980 6972 8092 7861
  17   18   19   20   21   22   23   24   25   26
3234 3432 3564 6188 6188 6664 6006  693 2541 3003

# Creating the Stok_nommer column

  Stok_id Blok_id Blok_nommer
1 1       1       1
2 2       1       1
3 3       1       1
4 4       1       1
5 5       1       1
6 6       1       1

In [19]:
# Let's write the big boy into a .xlsx file;

write.xlsx(blok_inligting_dat , "G:\\My Drive\\Programming\\Datasets\\blok_info_dat.xlsx")